// Auto-generated by LibreLane
module uart2gpi(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_ni,
  input uart_rx_i,
  output uart_tx_o,
  input[3:0] gpio_i,
  output[3:0] gpio_o,
  output[3:0] gpio_oe,
  output[1:0] pwm_o,
  input i2c_scl_i,
  output i2c_scl_o,
  output i2c_scl_oe,
  input i2c_sda_i,
  output i2c_sda_o,
  output i2c_sda_oe
);
endmodule
