// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure
`timescale 1ns / 1ps


package i2c_reg_pkg;

  // Param list
  parameter int FifoDepth = 8;
  // parameter int AcqFifoDepth = 2;
  // parameter int NumAlerts = 1;

  // Address widths within the block
  parameter int BlockAw = 7;

  // Number of registers for every interface
  // parameter int NumRegs = 16;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } tx_stretch_ctrl_en;
    struct packed {
      logic        q;
    } multi_controller_monitor_en;
    struct packed {
      logic        q;
    } ack_ctrl_en;
    struct packed {
      logic        q;
    } nack_addr_after_timeout;
    struct packed {
      logic        q;
    } llpbk;
    struct packed {
      logic        q;
    } enabletarget;
    struct packed {
      logic        q;
    } enablehost;
  } i2c_reg2hw_ctrl_reg_t;

  typedef struct packed {
    logic [7:0]  q;
    logic        re;
  } i2c_reg2hw_rdata_reg_t;

  typedef struct packed {
    struct packed {
      logic        q; // 0
      logic        qe;
    } nakok;
    struct packed {
      logic        q;
      logic        qe;
    } rcont;
    struct packed {
      logic        q;
      logic        qe;
    } readb;
    struct packed {
      logic        q;
      logic        qe;
    } stop;
    struct packed {
      logic        q;
      logic        qe;
    } start;
    struct packed {
      logic [7:0]  q;
      logic        qe;
    } fbyte;
  } i2c_reg2hw_fdata_reg_t;

  typedef struct packed {

    struct packed {
      logic        q;
      logic        qe;
    } fmtrst;
    struct packed {
      logic        q;
      logic        qe;
    } rxrst;
  } i2c_reg2hw_fifo_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic [12:0] q;
    } tlow;
    struct packed {
      logic [12:0] q;
    } thigh;
  } i2c_reg2hw_timing0_reg_t;

  typedef struct packed {
    struct packed {
      logic [8:0]  q;
    } t_f;
    struct packed {
      logic [9:0] q;
    } t_r;
  } i2c_reg2hw_timing1_reg_t;

  typedef struct packed {
    struct packed {
      logic [12:0] q;
    } thd_sta;
    struct packed {
      logic [12:0] q;
    } tsu_sta;
  } i2c_reg2hw_timing2_reg_t;

  typedef struct packed {
    struct packed {
      logic [12:0] q;
    } thd_dat;
    struct packed {
      logic [8:0]  q;
    } tsu_dat;
  } i2c_reg2hw_timing3_reg_t;

  typedef struct packed {
    struct packed {
      logic [12:0] q;
    } t_buf;
    struct packed {
      logic [12:0] q;
    } tsu_sto;
  } i2c_reg2hw_timing4_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } en;
    struct packed {
      logic        q;
    } mode;
    struct packed {
      logic [29:0] q;
    } val;
  } i2c_reg2hw_timeout_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } en;
    struct packed {
      logic [30:0] q;
    } val;
  } i2c_reg2hw_host_nack_handler_timeout_reg_t;
  
  typedef struct packed {
    struct packed {
      logic        d;
    } rxempty;
    struct packed {
      logic        d;
    } hostidle;
    struct packed {
      logic        d;
    } fmtempty;
    struct packed {
      logic        d;
    } rxfull;
    struct packed {
      logic        d;
    } fmtfull;
  } i2c_hw2reg_status_reg_t;

  typedef struct packed {
    logic [7:0]  d;
  } i2c_hw2reg_rdata_reg_t;

  typedef struct packed {
    struct packed {
      logic [11:0] d;
    } rxlvl;
    struct packed {
      logic [11:0] d;
    } fmtlvl;
  } i2c_hw2reg_host_fifo_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } arbitration_lost;
    struct packed {
      logic        d;
      logic        de;
    } bus_timeout;
    struct packed {
      logic        d;
      logic        de;
    } unhandled_nack_timeout;
    struct packed {
      logic        d;
      logic        de;
    } nack;
  } i2c_hw2reg_controller_events_reg_t;



  // Register -> HW type
  typedef struct packed {
    i2c_reg2hw_ctrl_reg_t ctrl; // [409:403]                                             <--  /1   / Control.
    i2c_reg2hw_rdata_reg_t rdata; // [402:394]                                           <--  /2   / RX data register (Copied from hw2reg into SW side).
    i2c_reg2hw_fdata_reg_t fdata; // [393:375]                                           <--  /3   / Format data Register.
    i2c_reg2hw_fifo_ctrl_reg_t fifo_ctrl; // [374:367]                                   <--  /4          / FIFOS Reset (ALL)).
    i2c_reg2hw_timing0_reg_t timing0; // [311:286]                                       <--  /5   / TIMING: (HOST) (tlow & thigh)
    i2c_reg2hw_timing1_reg_t timing1; // [285:267]                                       <--  /6   / TIMING: Signal rise and fall time compensation
    i2c_reg2hw_timing2_reg_t timing2; // [266:241]                                       <--  /7        / TIMING: Start hold time & start setup time
    i2c_reg2hw_timing3_reg_t timing3; // [240:219]                                       <--  /8        / TIMING: Data hold time & Data setup / 1.timethd_dat → “keep data stable after SCL falls.”  2.tsu_dat → “set data up early before SCL rises.”
    i2c_reg2hw_timing4_reg_t timing4; // [218:193]                                       <--  /9        / TIMING: Bus Free time & Stop condition setup time
    i2c_reg2hw_timeout_ctrl_reg_t timeout_ctrl; // [192:161]                             <--  /10         / Control timeout and activation of clock stretching feature
    i2c_reg2hw_host_nack_handler_timeout_reg_t host_nack_handler_timeout; // [38:7]      <--  /11
  } i2c_reg2hw_t;


  // HW -> register type
  typedef struct packed {
    i2c_hw2reg_status_reg_t status; // [149:139]                                         <--  /1   / STATUSES: fifo full, empty, host idle, target idle, etc
    i2c_hw2reg_rdata_reg_t rdata; // [138:131]                                           <--  /2   / Host (Mode): Received Data from connected slave
    i2c_hw2reg_host_fifo_status_reg_t host_fifo_status; // [130:107]                               / Host (Mode): Fifo Levels
    i2c_hw2reg_controller_events_reg_t controller_events; // [13:6]                      <--  /3   / HOST (Mode): Controller events , Reveived NACK, etc
  } i2c_hw2reg_t;



  // Register offsets (reg2hw)
  parameter logic [BlockAw-1:0] I2C_CTRL_OFFSET = 7'h 10;
  parameter logic [BlockAw-1:0] I2C_FDATA_OFFSET = 7'h 1c;
  parameter logic [BlockAw-1:0] I2C_FIFO_CTRL_OFFSET = 7'h 20;
  parameter logic [BlockAw-1:0] I2C_TIMING0_OFFSET = 7'h 3c;
  parameter logic [BlockAw-1:0] I2C_TIMING1_OFFSET = 7'h 40;
  parameter logic [BlockAw-1:0] I2C_TIMING2_OFFSET = 7'h 44;
  parameter logic [BlockAw-1:0] I2C_TIMING3_OFFSET = 7'h 48;
  parameter logic [BlockAw-1:0] I2C_TIMING4_OFFSET = 7'h 4c;
  parameter logic [BlockAw-1:0] I2C_TIMEOUT_CTRL_OFFSET = 7'h 50;
  parameter logic [BlockAw-1:0] I2C_HOST_NACK_HANDLER_TIMEOUT_OFFSET = 7'h 74;

  // Register offsets (hw2reg)
  parameter logic [BlockAw-1:0] I2C_STATUS_OFFSET = 7'h 14;
  parameter logic [BlockAw-1:0] I2C_RDATA_OFFSET = 7'h 18;
  parameter logic [BlockAw-1:0] I2C_HOST_FIFO_STATUS_OFFSET = 7'h 2c;
  parameter logic [BlockAw-1:0] I2C_CONTROLLER_EVENTS_OFFSET = 7'h 78;


  // Register index
  typedef enum int {
    I2C_CTRL,
    I2C_FDATA,
    I2C_FIFO_CTRL,
    I2C_TIMING0,
    I2C_TIMING1,
    I2C_TIMING2,
    I2C_TIMING3,
    I2C_TIMING4,
    I2C_TIMEOUT_CTRL,
    I2C_HOST_NACK_HANDLER_TIMEOUT,
    I2C_STATUS,
    I2C_RDATA_O,
    I2C_HOST_FIFO_STATUS,
    I2C_CONTROLLER_EVENTS
  } i2c_id_e;

endpackage
